<?php
/**
 * AgeRange
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * AgeRange Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgeRange
{
    /**
     * Possible values of this enum
     */
    const BELOW_TWENTY_FIVE = 'BelowTwentyFive';
    const TWENTY_FIVE_TO_THIRTY_FOUR = 'TwentyFiveToThirtyFour';
    const THIRTY_FIVE_TO_FORTY_FOUR = 'ThirtyFiveToFortyFour';
    const FORTY_FIVE_TO_FIFTY_FOUR = 'FortyFiveToFiftyFour';
    const FIFTY_FIVE_TO_SIXTY_FOUR = 'FiftyFiveToSixtyFour';
    const SIXTY_FIVE_TO_SEVENTY_FOUR = 'SixtyFiveToSeventyFour';
    const SEVENTY_FIVE_AND_OLDER = 'SeventyFiveAndOlder';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BELOW_TWENTY_FIVE,
            self::TWENTY_FIVE_TO_THIRTY_FOUR,
            self::THIRTY_FIVE_TO_FORTY_FOUR,
            self::FORTY_FIVE_TO_FIFTY_FOUR,
            self::FIFTY_FIVE_TO_SIXTY_FOUR,
            self::SIXTY_FIVE_TO_SEVENTY_FOUR,
            self::SEVENTY_FIVE_AND_OLDER,
        ];
    }
}


