<?php
/**
 * InvoiceDueTerm
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * InvoiceDueTerm Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoiceDueTerm
{
    /**
     * Possible values of this enum
     */
    const AFTER3_DAYS = 'After3Days';
    const AFTER7_DAYS = 'After7Days';
    const AFTER14_DAYS = 'After14Days';
    const AFTER21_DAYS = 'After21Days';
    const AFTER28_DAYS = 'After28Days';
    const AFTER1_MONTH = 'After1Month';
    const AFTER2_MONTHS = 'After2Months';
    const TRANSPORT_DATE = 'TransportDate';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AFTER3_DAYS,
            self::AFTER7_DAYS,
            self::AFTER14_DAYS,
            self::AFTER21_DAYS,
            self::AFTER28_DAYS,
            self::AFTER1_MONTH,
            self::AFTER2_MONTHS,
            self::TRANSPORT_DATE,
        ];
    }
}


