<?php
/**
 * ListOfGoodsValue
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * ListOfGoodsValue Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListOfGoodsValue implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ListOfGoodsValue';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
        'list_of_goods_type' => '\Swagger\Client\Model\FloorFloorType',
        'take_over_specification' => '\Swagger\Client\Model\TakeOverSpecification',
        'sub_entries' => '\Swagger\Client\Model\ListOfGoodsValue[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
        'list_of_goods_type' => null,
        'take_over_specification' => null,
        'sub_entries' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'list_of_goods_type' => 'listOfGoodsType',
        'take_over_specification' => 'takeOverSpecification',
        'sub_entries' => 'subEntries'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'list_of_goods_type' => 'setListOfGoodsType',
        'take_over_specification' => 'setTakeOverSpecification',
        'sub_entries' => 'setSubEntries'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'list_of_goods_type' => 'getListOfGoodsType',
        'take_over_specification' => 'getTakeOverSpecification',
        'sub_entries' => 'getSubEntries'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['list_of_goods_type'] = isset($data['list_of_goods_type']) ? $data['list_of_goods_type'] : null;
        $this->container['take_over_specification'] = isset($data['take_over_specification']) ? $data['take_over_specification'] : null;
        $this->container['sub_entries'] = isset($data['sub_entries']) ? $data['sub_entries'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        if ($this->container['list_of_goods_type'] === null) {
            $invalidProperties[] = "'list_of_goods_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets list_of_goods_type
     *
     * @return \Swagger\Client\Model\FloorFloorType
     */
    public function getListOfGoodsType()
    {
        return $this->container['list_of_goods_type'];
    }

    /**
     * Sets list_of_goods_type
     *
     * @param \Swagger\Client\Model\FloorFloorType $list_of_goods_type list_of_goods_type
     *
     * @return $this
     */
    public function setListOfGoodsType($list_of_goods_type)
    {
        $this->container['list_of_goods_type'] = $list_of_goods_type;

        return $this;
    }

    /**
     * Gets take_over_specification
     *
     * @return \Swagger\Client\Model\TakeOverSpecification
     */
    public function getTakeOverSpecification()
    {
        return $this->container['take_over_specification'];
    }

    /**
     * Sets take_over_specification
     *
     * @param \Swagger\Client\Model\TakeOverSpecification $take_over_specification take_over_specification
     *
     * @return $this
     */
    public function setTakeOverSpecification($take_over_specification)
    {
        $this->container['take_over_specification'] = $take_over_specification;

        return $this;
    }

    /**
     * Gets sub_entries
     *
     * @return \Swagger\Client\Model\ListOfGoodsValue[]
     */
    public function getSubEntries()
    {
        return $this->container['sub_entries'];
    }

    /**
     * Sets sub_entries
     *
     * @param \Swagger\Client\Model\ListOfGoodsValue[] $sub_entries sub_entries
     *
     * @return $this
     */
    public function setSubEntries($sub_entries)
    {
        $this->container['sub_entries'] = $sub_entries;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


