<?php
/**
 * LocationPlace
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * LocationPlace Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LocationPlace
{
    /**
     * Possible values of this enum
     */
    const FOREST_EDGE = 'ForestEdge';
    const WATERSIDE = 'Waterside';
    const PARK = 'Park';
    const ON_BUSY_STREET = 'OnBusyStreet';
    const ON_QUIET_STREET = 'OnQuietStreet';
    const CENTRAL_CITY_CENTER = 'CentralCityCenter';
    const RESIDENTIAL_AREA = 'ResidentialArea';
    const UNOBSTRUCTED_VIEW = 'UnobstructedView';
    const SHELTERED_LOCATION = 'ShelteredLocation';
    const OPEN_AREA = 'OpenArea';
    const OUTSIDE_VILLAGE = 'OutsideVillage';
    const ON_WATERWAY = 'OnWaterway';
    const FORESTED_AREA = 'ForestedArea';
    const NEAR_RAILWAY_STATION = 'NearRailwayStation';
    const SUBURB = 'Suburb';
    const BUSINESS_PARK = 'BusinessPark';
    const OTHER = 'Other';
    const LRTE = 'LRTE';
    const HARBOR_AREA = 'HarborArea';
    const INDUSTRIAL_AREA = 'IndustrialArea';
    const OFFICE_PARK = 'OfficePark';
    const PRTE = 'PRTE';
    const SHOPPING_CENTER = 'ShoppingCenter';
    const COUNTRYSIDE = 'Countryside';
    const NEAR_HIGHWAY = 'NearHighway';
    const NEAR_PUBLIC_TRANSPORT = 'NearPublicTransport';
    const NEAR_SCHOOL = 'NearSchool';
    const SEASIDE = 'Seaside';
    const SECLUDED_LOCATION = 'SecludedLocation';
    const STANDALONE = 'Standalone';
    const SUB_DIVISION = 'SubDivision';
    const FURNITURE_BOULEVARD = 'FurnitureBoulevard';
    const INDOOR_SHOPPING = 'IndoorShopping';
    const SEA_VIEW = 'SeaView';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FOREST_EDGE,
            self::WATERSIDE,
            self::PARK,
            self::ON_BUSY_STREET,
            self::ON_QUIET_STREET,
            self::CENTRAL_CITY_CENTER,
            self::RESIDENTIAL_AREA,
            self::UNOBSTRUCTED_VIEW,
            self::SHELTERED_LOCATION,
            self::OPEN_AREA,
            self::OUTSIDE_VILLAGE,
            self::ON_WATERWAY,
            self::FORESTED_AREA,
            self::NEAR_RAILWAY_STATION,
            self::SUBURB,
            self::BUSINESS_PARK,
            self::OTHER,
            self::LRTE,
            self::HARBOR_AREA,
            self::INDUSTRIAL_AREA,
            self::OFFICE_PARK,
            self::PRTE,
            self::SHOPPING_CENTER,
            self::COUNTRYSIDE,
            self::NEAR_HIGHWAY,
            self::NEAR_PUBLIC_TRANSPORT,
            self::NEAR_SCHOOL,
            self::SEASIDE,
            self::SECLUDED_LOCATION,
            self::STANDALONE,
            self::SUB_DIVISION,
            self::FURNITURE_BOULEVARD,
            self::INDOOR_SHOPPING,
            self::SEA_VIEW,
        ];
    }
}


