<?php
/**
 * MediaContractStatus
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * MediaContractStatus Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MediaContractStatus
{
    /**
     * Possible values of this enum
     */
    const INACTIVE = 'Inactive';
    const PENDING_ACTIVATION = 'PendingActivation';
    const ACTIVE = 'Active';
    const DENIED = 'Denied';
    const SUSPENDED = 'Suspended';
    const PENDING_DEACTIVATION = 'PendingDeactivation';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INACTIVE,
            self::PENDING_ACTIVATION,
            self::ACTIVE,
            self::DENIED,
            self::SUSPENDED,
            self::PENDING_DEACTIVATION,
        ];
    }
}


