<?php
/**
 * MessageSnapShot
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * MessageSnapShot Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessageSnapShot extends Entity 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'MessageSnapShot';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'assignment_city' => 'string',
        'assignment_house_number' => 'string',
        'assignment_street_name' => 'string',
        'city' => 'string',
        'date_time_created' => '\DateTime',
        'date_time_modified' => '\DateTime',
        'email_address' => 'string',
        'first_name' => 'string',
        'gender' => '\Swagger\Client\Model\Gender',
        'has_been_read' => 'bool',
        'house_number' => 'int',
        'info_url' => 'string',
        'last_name' => 'string',
        'linked_assignment' => '\Swagger\Client\Model\LinkedAssignment',
        'linked_relation' => '\Swagger\Client\Model\LinkedRelation',
        'linked_media_contract' => '\Swagger\Client\Model\LinkedMediaContract',
        'linked_search_assignment' => '\Swagger\Client\Model\LinkedSearchAssignment',
        'linked_created_by' => '\Swagger\Client\Model\LinkedEmployee',
        'linked_modified_by' => '\Swagger\Client\Model\LinkedEmployee',
        'message_type' => '\Swagger\Client\Model\MessageType',
        'mobile_phone_number' => 'string',
        'phone_number' => 'string',
        'postal_code' => 'string',
        'real_estate_agency_id' => 'string',
        'region' => 'string',
        'sender' => 'string',
        'street_name' => 'string',
        'subject' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'assignment_city' => null,
        'assignment_house_number' => null,
        'assignment_street_name' => null,
        'city' => null,
        'date_time_created' => 'date-time',
        'date_time_modified' => 'date-time',
        'email_address' => null,
        'first_name' => null,
        'gender' => null,
        'has_been_read' => null,
        'house_number' => 'int32',
        'info_url' => null,
        'last_name' => null,
        'linked_assignment' => null,
        'linked_relation' => null,
        'linked_media_contract' => null,
        'linked_search_assignment' => null,
        'linked_created_by' => null,
        'linked_modified_by' => null,
        'message_type' => null,
        'mobile_phone_number' => null,
        'phone_number' => null,
        'postal_code' => null,
        'real_estate_agency_id' => 'guid',
        'region' => null,
        'sender' => null,
        'street_name' => null,
        'subject' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'assignment_city' => 'assignmentCity',
        'assignment_house_number' => 'assignmentHouseNumber',
        'assignment_street_name' => 'assignmentStreetName',
        'city' => 'city',
        'date_time_created' => 'dateTimeCreated',
        'date_time_modified' => 'dateTimeModified',
        'email_address' => 'emailAddress',
        'first_name' => 'firstName',
        'gender' => 'gender',
        'has_been_read' => 'hasBeenRead',
        'house_number' => 'houseNumber',
        'info_url' => 'infoUrl',
        'last_name' => 'lastName',
        'linked_assignment' => 'linkedAssignment',
        'linked_relation' => 'linkedRelation',
        'linked_media_contract' => 'linkedMediaContract',
        'linked_search_assignment' => 'linkedSearchAssignment',
        'linked_created_by' => 'linkedCreatedBy',
        'linked_modified_by' => 'linkedModifiedBy',
        'message_type' => 'messageType',
        'mobile_phone_number' => 'mobilePhoneNumber',
        'phone_number' => 'phoneNumber',
        'postal_code' => 'postalCode',
        'real_estate_agency_id' => 'realEstateAgencyId',
        'region' => 'region',
        'sender' => 'sender',
        'street_name' => 'streetName',
        'subject' => 'subject'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'assignment_city' => 'setAssignmentCity',
        'assignment_house_number' => 'setAssignmentHouseNumber',
        'assignment_street_name' => 'setAssignmentStreetName',
        'city' => 'setCity',
        'date_time_created' => 'setDateTimeCreated',
        'date_time_modified' => 'setDateTimeModified',
        'email_address' => 'setEmailAddress',
        'first_name' => 'setFirstName',
        'gender' => 'setGender',
        'has_been_read' => 'setHasBeenRead',
        'house_number' => 'setHouseNumber',
        'info_url' => 'setInfoUrl',
        'last_name' => 'setLastName',
        'linked_assignment' => 'setLinkedAssignment',
        'linked_relation' => 'setLinkedRelation',
        'linked_media_contract' => 'setLinkedMediaContract',
        'linked_search_assignment' => 'setLinkedSearchAssignment',
        'linked_created_by' => 'setLinkedCreatedBy',
        'linked_modified_by' => 'setLinkedModifiedBy',
        'message_type' => 'setMessageType',
        'mobile_phone_number' => 'setMobilePhoneNumber',
        'phone_number' => 'setPhoneNumber',
        'postal_code' => 'setPostalCode',
        'real_estate_agency_id' => 'setRealEstateAgencyId',
        'region' => 'setRegion',
        'sender' => 'setSender',
        'street_name' => 'setStreetName',
        'subject' => 'setSubject'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'assignment_city' => 'getAssignmentCity',
        'assignment_house_number' => 'getAssignmentHouseNumber',
        'assignment_street_name' => 'getAssignmentStreetName',
        'city' => 'getCity',
        'date_time_created' => 'getDateTimeCreated',
        'date_time_modified' => 'getDateTimeModified',
        'email_address' => 'getEmailAddress',
        'first_name' => 'getFirstName',
        'gender' => 'getGender',
        'has_been_read' => 'getHasBeenRead',
        'house_number' => 'getHouseNumber',
        'info_url' => 'getInfoUrl',
        'last_name' => 'getLastName',
        'linked_assignment' => 'getLinkedAssignment',
        'linked_relation' => 'getLinkedRelation',
        'linked_media_contract' => 'getLinkedMediaContract',
        'linked_search_assignment' => 'getLinkedSearchAssignment',
        'linked_created_by' => 'getLinkedCreatedBy',
        'linked_modified_by' => 'getLinkedModifiedBy',
        'message_type' => 'getMessageType',
        'mobile_phone_number' => 'getMobilePhoneNumber',
        'phone_number' => 'getPhoneNumber',
        'postal_code' => 'getPostalCode',
        'real_estate_agency_id' => 'getRealEstateAgencyId',
        'region' => 'getRegion',
        'sender' => 'getSender',
        'street_name' => 'getStreetName',
        'subject' => 'getSubject'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['assignment_city'] = isset($data['assignment_city']) ? $data['assignment_city'] : null;
        $this->container['assignment_house_number'] = isset($data['assignment_house_number']) ? $data['assignment_house_number'] : null;
        $this->container['assignment_street_name'] = isset($data['assignment_street_name']) ? $data['assignment_street_name'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['date_time_created'] = isset($data['date_time_created']) ? $data['date_time_created'] : null;
        $this->container['date_time_modified'] = isset($data['date_time_modified']) ? $data['date_time_modified'] : null;
        $this->container['email_address'] = isset($data['email_address']) ? $data['email_address'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['gender'] = isset($data['gender']) ? $data['gender'] : null;
        $this->container['has_been_read'] = isset($data['has_been_read']) ? $data['has_been_read'] : null;
        $this->container['house_number'] = isset($data['house_number']) ? $data['house_number'] : null;
        $this->container['info_url'] = isset($data['info_url']) ? $data['info_url'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['linked_assignment'] = isset($data['linked_assignment']) ? $data['linked_assignment'] : null;
        $this->container['linked_relation'] = isset($data['linked_relation']) ? $data['linked_relation'] : null;
        $this->container['linked_media_contract'] = isset($data['linked_media_contract']) ? $data['linked_media_contract'] : null;
        $this->container['linked_search_assignment'] = isset($data['linked_search_assignment']) ? $data['linked_search_assignment'] : null;
        $this->container['linked_created_by'] = isset($data['linked_created_by']) ? $data['linked_created_by'] : null;
        $this->container['linked_modified_by'] = isset($data['linked_modified_by']) ? $data['linked_modified_by'] : null;
        $this->container['message_type'] = isset($data['message_type']) ? $data['message_type'] : null;
        $this->container['mobile_phone_number'] = isset($data['mobile_phone_number']) ? $data['mobile_phone_number'] : null;
        $this->container['phone_number'] = isset($data['phone_number']) ? $data['phone_number'] : null;
        $this->container['postal_code'] = isset($data['postal_code']) ? $data['postal_code'] : null;
        $this->container['real_estate_agency_id'] = isset($data['real_estate_agency_id']) ? $data['real_estate_agency_id'] : null;
        $this->container['region'] = isset($data['region']) ? $data['region'] : null;
        $this->container['sender'] = isset($data['sender']) ? $data['sender'] : null;
        $this->container['street_name'] = isset($data['street_name']) ? $data['street_name'] : null;
        $this->container['subject'] = isset($data['subject']) ? $data['subject'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets assignment_city
     *
     * @return string
     */
    public function getAssignmentCity()
    {
        return $this->container['assignment_city'];
    }

    /**
     * Sets assignment_city
     *
     * @param string $assignment_city assignment_city
     *
     * @return $this
     */
    public function setAssignmentCity($assignment_city)
    {
        $this->container['assignment_city'] = $assignment_city;

        return $this;
    }

    /**
     * Gets assignment_house_number
     *
     * @return string
     */
    public function getAssignmentHouseNumber()
    {
        return $this->container['assignment_house_number'];
    }

    /**
     * Sets assignment_house_number
     *
     * @param string $assignment_house_number assignment_house_number
     *
     * @return $this
     */
    public function setAssignmentHouseNumber($assignment_house_number)
    {
        $this->container['assignment_house_number'] = $assignment_house_number;

        return $this;
    }

    /**
     * Gets assignment_street_name
     *
     * @return string
     */
    public function getAssignmentStreetName()
    {
        return $this->container['assignment_street_name'];
    }

    /**
     * Sets assignment_street_name
     *
     * @param string $assignment_street_name assignment_street_name
     *
     * @return $this
     */
    public function setAssignmentStreetName($assignment_street_name)
    {
        $this->container['assignment_street_name'] = $assignment_street_name;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return $this
     */
    public function setCity($city)
    {
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets date_time_created
     *
     * @return \DateTime
     */
    public function getDateTimeCreated()
    {
        return $this->container['date_time_created'];
    }

    /**
     * Sets date_time_created
     *
     * @param \DateTime $date_time_created date_time_created
     *
     * @return $this
     */
    public function setDateTimeCreated($date_time_created)
    {
        $this->container['date_time_created'] = $date_time_created;

        return $this;
    }

    /**
     * Gets date_time_modified
     *
     * @return \DateTime
     */
    public function getDateTimeModified()
    {
        return $this->container['date_time_modified'];
    }

    /**
     * Sets date_time_modified
     *
     * @param \DateTime $date_time_modified date_time_modified
     *
     * @return $this
     */
    public function setDateTimeModified($date_time_modified)
    {
        $this->container['date_time_modified'] = $date_time_modified;

        return $this;
    }

    /**
     * Gets email_address
     *
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->container['email_address'];
    }

    /**
     * Sets email_address
     *
     * @param string $email_address email_address
     *
     * @return $this
     */
    public function setEmailAddress($email_address)
    {
        $this->container['email_address'] = $email_address;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name first_name
     *
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return \Swagger\Client\Model\Gender
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param \Swagger\Client\Model\Gender $gender gender
     *
     * @return $this
     */
    public function setGender($gender)
    {
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets has_been_read
     *
     * @return bool
     */
    public function getHasBeenRead()
    {
        return $this->container['has_been_read'];
    }

    /**
     * Sets has_been_read
     *
     * @param bool $has_been_read has_been_read
     *
     * @return $this
     */
    public function setHasBeenRead($has_been_read)
    {
        $this->container['has_been_read'] = $has_been_read;

        return $this;
    }

    /**
     * Gets house_number
     *
     * @return int
     */
    public function getHouseNumber()
    {
        return $this->container['house_number'];
    }

    /**
     * Sets house_number
     *
     * @param int $house_number house_number
     *
     * @return $this
     */
    public function setHouseNumber($house_number)
    {
        $this->container['house_number'] = $house_number;

        return $this;
    }

    /**
     * Gets info_url
     *
     * @return string
     */
    public function getInfoUrl()
    {
        return $this->container['info_url'];
    }

    /**
     * Sets info_url
     *
     * @param string $info_url info_url
     *
     * @return $this
     */
    public function setInfoUrl($info_url)
    {
        $this->container['info_url'] = $info_url;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name last_name
     *
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets linked_assignment
     *
     * @return \Swagger\Client\Model\LinkedAssignment
     */
    public function getLinkedAssignment()
    {
        return $this->container['linked_assignment'];
    }

    /**
     * Sets linked_assignment
     *
     * @param \Swagger\Client\Model\LinkedAssignment $linked_assignment linked_assignment
     *
     * @return $this
     */
    public function setLinkedAssignment($linked_assignment)
    {
        $this->container['linked_assignment'] = $linked_assignment;

        return $this;
    }

    /**
     * Gets linked_relation
     *
     * @return \Swagger\Client\Model\LinkedRelation
     */
    public function getLinkedRelation()
    {
        return $this->container['linked_relation'];
    }

    /**
     * Sets linked_relation
     *
     * @param \Swagger\Client\Model\LinkedRelation $linked_relation linked_relation
     *
     * @return $this
     */
    public function setLinkedRelation($linked_relation)
    {
        $this->container['linked_relation'] = $linked_relation;

        return $this;
    }

    /**
     * Gets linked_media_contract
     *
     * @return \Swagger\Client\Model\LinkedMediaContract
     */
    public function getLinkedMediaContract()
    {
        return $this->container['linked_media_contract'];
    }

    /**
     * Sets linked_media_contract
     *
     * @param \Swagger\Client\Model\LinkedMediaContract $linked_media_contract linked_media_contract
     *
     * @return $this
     */
    public function setLinkedMediaContract($linked_media_contract)
    {
        $this->container['linked_media_contract'] = $linked_media_contract;

        return $this;
    }

    /**
     * Gets linked_search_assignment
     *
     * @return \Swagger\Client\Model\LinkedSearchAssignment
     */
    public function getLinkedSearchAssignment()
    {
        return $this->container['linked_search_assignment'];
    }

    /**
     * Sets linked_search_assignment
     *
     * @param \Swagger\Client\Model\LinkedSearchAssignment $linked_search_assignment linked_search_assignment
     *
     * @return $this
     */
    public function setLinkedSearchAssignment($linked_search_assignment)
    {
        $this->container['linked_search_assignment'] = $linked_search_assignment;

        return $this;
    }

    /**
     * Gets linked_created_by
     *
     * @return \Swagger\Client\Model\LinkedEmployee
     */
    public function getLinkedCreatedBy()
    {
        return $this->container['linked_created_by'];
    }

    /**
     * Sets linked_created_by
     *
     * @param \Swagger\Client\Model\LinkedEmployee $linked_created_by linked_created_by
     *
     * @return $this
     */
    public function setLinkedCreatedBy($linked_created_by)
    {
        $this->container['linked_created_by'] = $linked_created_by;

        return $this;
    }

    /**
     * Gets linked_modified_by
     *
     * @return \Swagger\Client\Model\LinkedEmployee
     */
    public function getLinkedModifiedBy()
    {
        return $this->container['linked_modified_by'];
    }

    /**
     * Sets linked_modified_by
     *
     * @param \Swagger\Client\Model\LinkedEmployee $linked_modified_by linked_modified_by
     *
     * @return $this
     */
    public function setLinkedModifiedBy($linked_modified_by)
    {
        $this->container['linked_modified_by'] = $linked_modified_by;

        return $this;
    }

    /**
     * Gets message_type
     *
     * @return \Swagger\Client\Model\MessageType
     */
    public function getMessageType()
    {
        return $this->container['message_type'];
    }

    /**
     * Sets message_type
     *
     * @param \Swagger\Client\Model\MessageType $message_type message_type
     *
     * @return $this
     */
    public function setMessageType($message_type)
    {
        $this->container['message_type'] = $message_type;

        return $this;
    }

    /**
     * Gets mobile_phone_number
     *
     * @return string
     */
    public function getMobilePhoneNumber()
    {
        return $this->container['mobile_phone_number'];
    }

    /**
     * Sets mobile_phone_number
     *
     * @param string $mobile_phone_number mobile_phone_number
     *
     * @return $this
     */
    public function setMobilePhoneNumber($mobile_phone_number)
    {
        $this->container['mobile_phone_number'] = $mobile_phone_number;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string $phone_number phone_number
     *
     * @return $this
     */
    public function setPhoneNumber($phone_number)
    {
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string $postal_code postal_code
     *
     * @return $this
     */
    public function setPostalCode($postal_code)
    {
        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets real_estate_agency_id
     *
     * @return string
     */
    public function getRealEstateAgencyId()
    {
        return $this->container['real_estate_agency_id'];
    }

    /**
     * Sets real_estate_agency_id
     *
     * @param string $real_estate_agency_id real_estate_agency_id
     *
     * @return $this
     */
    public function setRealEstateAgencyId($real_estate_agency_id)
    {
        $this->container['real_estate_agency_id'] = $real_estate_agency_id;

        return $this;
    }

    /**
     * Gets region
     *
     * @return string
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param string $region region
     *
     * @return $this
     */
    public function setRegion($region)
    {
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return string
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param string $sender sender
     *
     * @return $this
     */
    public function setSender($sender)
    {
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets street_name
     *
     * @return string
     */
    public function getStreetName()
    {
        return $this->container['street_name'];
    }

    /**
     * Sets street_name
     *
     * @param string $street_name street_name
     *
     * @return $this
     */
    public function setStreetName($street_name)
    {
        $this->container['street_name'] = $street_name;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string $subject subject
     *
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


