<?php
/**
 * MessageType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * MessageType Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MessageType
{
    /**
     * Possible values of this enum
     */
    const BACK_OFFICE = 'BackOffice';
    const CONNECTOR = 'Connector';
    const SUPPORT = 'Support';
    const MEMBER = 'Member';
    const SEARCH_PROFILE = 'SearchProfile';
    const CONTACT_ME = 'ContactMe';
    const BOOK_A_VISIT = 'BookAVisit';
    const DOWNLOAD_BROCHURE = 'DownloadBrochure';
    const OFFER_LISTING = 'OfferListing';
    const FAILED_PUBLICATION = 'FailedPublication';
    const SUCCESSFUL_PUBLICATION = 'SuccessfulPublication';
    const MEMBER_DELETED = 'MemberDeleted';
    const PERSONAL = 'Personal';
    const COMPANY = 'Company';
    const CONTACT_FORM = 'ContactForm';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BACK_OFFICE,
            self::CONNECTOR,
            self::SUPPORT,
            self::MEMBER,
            self::SEARCH_PROFILE,
            self::CONTACT_ME,
            self::BOOK_A_VISIT,
            self::DOWNLOAD_BROCHURE,
            self::OFFER_LISTING,
            self::FAILED_PUBLICATION,
            self::SUCCESSFUL_PUBLICATION,
            self::MEMBER_DELETED,
            self::PERSONAL,
            self::COMPANY,
            self::CONTACT_FORM,
        ];
    }
}


