<?php
/**
 * NatureRegistration
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * NatureRegistration Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class NatureRegistration
{
    /**
     * Possible values of this enum
     */
    const VOLUNTARILY_FOR_BUSINESS_ECONOMIC_REASONS = 'VoluntarilyForBusinessEconomicReasons';
    const VOLUNTARILY_FOR_PERSONAL_REASONS = 'VoluntarilyForPersonalReasons';
    const FORCED_DUE_TO_BUSINESS_ECONOMIC_REASONS = 'ForcedDueToBusinessEconomicReasons';
    const FORCED_DUE_TO_PERSONAL_REASONS = 'ForcedDueToPersonalReasons';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VOLUNTARILY_FOR_BUSINESS_ECONOMIC_REASONS,
            self::VOLUNTARILY_FOR_PERSONAL_REASONS,
            self::FORCED_DUE_TO_BUSINESS_ECONOMIC_REASONS,
            self::FORCED_DUE_TO_PERSONAL_REASONS,
        ];
    }
}


