<?php
/**
 * RelationGroupType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * RelationGroupType Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RelationGroupType
{
    /**
     * Possible values of this enum
     */
    const USER_DEFINED = 'UserDefined';
    const HOUSE_HUNTERS = 'HouseHunters';
    const WEBSITE_VISITORS = 'WebsiteVisitors';
    const NOTARIES = 'Notaries';
    const TENANTS = 'Tenants';
    const PURCHASERS = 'Purchasers';
    const LESSORS = 'Lessors';
    const VENDORS = 'Vendors';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::USER_DEFINED,
            self::HOUSE_HUNTERS,
            self::WEBSITE_VISITORS,
            self::NOTARIES,
            self::TENANTS,
            self::PURCHASERS,
            self::LESSORS,
            self::VENDORS,
        ];
    }
}


