<?php
/**
 * SpaceType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * SpaceType Class Doc Comment
 *
 * @category Class
 * @description 
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SpaceType
{
    /**
     * Possible values of this enum
     */
    const KITCHEN = 'Kitchen';
    const BATHROOM = 'Bathroom';
    const BALCONY = 'Balcony';
    const ROOF_TERRACE = 'RoofTerrace';
    const BEDROOM = 'Bedroom';
    const LIVING_ROOM = 'LivingRoom';
    const UTILITY_ROOM = 'UtilityRoom';
    const SHOWER = 'Shower';
    const TOILET = 'Toilet';
    const CORRIDOR = 'Corridor';
    const ENCLOSED_PORCH = 'EnclosedPorch';
    const HALL = 'Hall';
    const BOILER_ROOM = 'BoilerRoom';
    const STORE_ROOM = 'StoreRoom';
    const STORAGE = 'Storage';
    const DORMER = 'Dormer';
    const LOGGIA = 'Loggia';
    const VESTIBULE = 'Vestibule';
    const LAUNDRY_ROOM = 'LaundryRoom';
    const CONSERVATORY = 'Conservatory';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::KITCHEN,
            self::BATHROOM,
            self::BALCONY,
            self::ROOF_TERRACE,
            self::BEDROOM,
            self::LIVING_ROOM,
            self::UTILITY_ROOM,
            self::SHOWER,
            self::TOILET,
            self::CORRIDOR,
            self::ENCLOSED_PORCH,
            self::HALL,
            self::BOILER_ROOM,
            self::STORE_ROOM,
            self::STORAGE,
            self::DORMER,
            self::LOGGIA,
            self::VESTIBULE,
            self::LAUNDRY_ROOM,
            self::CONSERVATORY,
        ];
    }
}


