<?php
/**
 * TasksSearchRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * TasksSearchRequest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksSearchRequest extends SearchRequest 
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TasksSearchRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'category_ids' => 'string[]',
        'delegate_filter' => 'object',
        'employee_id' => 'string',
        'employee_ids' => 'string[]',
        'include_statistics' => 'bool',
        'order_by' => 'object',
        'status_filter' => '\Swagger\Client\Model\TaskStatus[]',
        'task_id' => 'string',
        'term_fields' => '\Swagger\Client\Model\TaskTermField[]',
        'task_ids' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'category_ids' => 'guid',
        'delegate_filter' => null,
        'employee_id' => 'guid',
        'employee_ids' => 'guid',
        'include_statistics' => null,
        'order_by' => null,
        'status_filter' => null,
        'task_id' => 'guid',
        'term_fields' => null,
        'task_ids' => 'guid'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes + parent::swaggerTypes();
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats + parent::swaggerFormats();
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'category_ids' => 'categoryIds',
        'delegate_filter' => 'delegateFilter',
        'employee_id' => 'employeeId',
        'employee_ids' => 'employeeIds',
        'include_statistics' => 'includeStatistics',
        'order_by' => 'orderBy',
        'status_filter' => 'statusFilter',
        'task_id' => 'taskId',
        'term_fields' => 'termFields',
        'task_ids' => 'taskIds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'category_ids' => 'setCategoryIds',
        'delegate_filter' => 'setDelegateFilter',
        'employee_id' => 'setEmployeeId',
        'employee_ids' => 'setEmployeeIds',
        'include_statistics' => 'setIncludeStatistics',
        'order_by' => 'setOrderBy',
        'status_filter' => 'setStatusFilter',
        'task_id' => 'setTaskId',
        'term_fields' => 'setTermFields',
        'task_ids' => 'setTaskIds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'category_ids' => 'getCategoryIds',
        'delegate_filter' => 'getDelegateFilter',
        'employee_id' => 'getEmployeeId',
        'employee_ids' => 'getEmployeeIds',
        'include_statistics' => 'getIncludeStatistics',
        'order_by' => 'getOrderBy',
        'status_filter' => 'getStatusFilter',
        'task_id' => 'getTaskId',
        'term_fields' => 'getTermFields',
        'task_ids' => 'getTaskIds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return parent::attributeMap() + self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return parent::setters() + self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return parent::getters() + self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    


    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        parent::__construct($data);

        $this->container['category_ids'] = isset($data['category_ids']) ? $data['category_ids'] : null;
        $this->container['delegate_filter'] = isset($data['delegate_filter']) ? $data['delegate_filter'] : null;
        $this->container['employee_id'] = isset($data['employee_id']) ? $data['employee_id'] : null;
        $this->container['employee_ids'] = isset($data['employee_ids']) ? $data['employee_ids'] : null;
        $this->container['include_statistics'] = isset($data['include_statistics']) ? $data['include_statistics'] : null;
        $this->container['order_by'] = isset($data['order_by']) ? $data['order_by'] : null;
        $this->container['status_filter'] = isset($data['status_filter']) ? $data['status_filter'] : null;
        $this->container['task_id'] = isset($data['task_id']) ? $data['task_id'] : null;
        $this->container['term_fields'] = isset($data['term_fields']) ? $data['term_fields'] : null;
        $this->container['task_ids'] = isset($data['task_ids']) ? $data['task_ids'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = parent::listInvalidProperties();

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets category_ids
     *
     * @return string[]
     */
    public function getCategoryIds()
    {
        return $this->container['category_ids'];
    }

    /**
     * Sets category_ids
     *
     * @param string[] $category_ids Only return tasks linked at one of the categories indicated by given Task category Id's.
     *
     * @return $this
     */
    public function setCategoryIds($category_ids)
    {
        $this->container['category_ids'] = $category_ids;

        return $this;
    }

    /**
     * Gets delegate_filter
     *
     * @return object
     */
    public function getDelegateFilter()
    {
        return $this->container['delegate_filter'];
    }

    /**
     * Sets delegate_filter
     *
     * @param object $delegate_filter Search the tasks created by the given employee (e.g. 'Tasks created by me') or assigned to given employee ('Tasks assigned to me') or both. Default: AssignedToMe
     *
     * @return $this
     */
    public function setDelegateFilter($delegate_filter)
    {
        $this->container['delegate_filter'] = $delegate_filter;

        return $this;
    }

    /**
     * Gets employee_id
     *
     * @return string
     */
    public function getEmployeeId()
    {
        return $this->container['employee_id'];
    }

    /**
     * Sets employee_id
     *
     * @param string $employee_id Search the tasks assigned and/or created by given employee.
     *
     * @return $this
     */
    public function setEmployeeId($employee_id)
    {
        $this->container['employee_id'] = $employee_id;

        return $this;
    }

    /**
     * Gets employee_ids
     *
     * @return string[]
     */
    public function getEmployeeIds()
    {
        return $this->container['employee_ids'];
    }

    /**
     * Sets employee_ids
     *
     * @param string[] $employee_ids Search the tasks assigned and/or created by given employee ids.
     *
     * @return $this
     */
    public function setEmployeeIds($employee_ids)
    {
        $this->container['employee_ids'] = $employee_ids;

        return $this;
    }

    /**
     * Gets include_statistics
     *
     * @return bool
     */
    public function getIncludeStatistics()
    {
        return $this->container['include_statistics'];
    }

    /**
     * Sets include_statistics
     *
     * @param bool $include_statistics Return statistics, like counts of timeline events in past, today and next week.
     *
     * @return $this
     */
    public function setIncludeStatistics($include_statistics)
    {
        $this->container['include_statistics'] = $include_statistics;

        return $this;
    }

    /**
     * Gets order_by
     *
     * @return object
     */
    public function getOrderBy()
    {
        return $this->container['order_by'];
    }

    /**
     * Sets order_by
     *
     * @param object $order_by Order the results by the indicated task field.
     *
     * @return $this
     */
    public function setOrderBy($order_by)
    {
        $this->container['order_by'] = $order_by;

        return $this;
    }

    /**
     * Gets status_filter
     *
     * @return \Swagger\Client\Model\TaskStatus[]
     */
    public function getStatusFilter()
    {
        return $this->container['status_filter'];
    }

    /**
     * Sets status_filter
     *
     * @param \Swagger\Client\Model\TaskStatus[] $status_filter Only return tasks with given status.
     *
     * @return $this
     */
    public function setStatusFilter($status_filter)
    {
        $this->container['status_filter'] = $status_filter;

        return $this;
    }

    /**
     * Gets task_id
     *
     * @return string
     */
    public function getTaskId()
    {
        return $this->container['task_id'];
    }

    /**
     * Sets task_id
     *
     * @param string $task_id Search by a specific task Id. Used to return/refresh one search result.
     *
     * @return $this
     */
    public function setTaskId($task_id)
    {
        $this->container['task_id'] = $task_id;

        return $this;
    }

    /**
     * Gets term_fields
     *
     * @return \Swagger\Client\Model\TaskTermField[]
     */
    public function getTermFields()
    {
        return $this->container['term_fields'];
    }

    /**
     * Sets term_fields
     *
     * @param \Swagger\Client\Model\TaskTermField[] $term_fields Search for given text (Term) indicated by the fields in the TermFields list. Required in case 'Term' is given.
     *
     * @return $this
     */
    public function setTermFields($term_fields)
    {
        $this->container['term_fields'] = $term_fields;

        return $this;
    }

    /**
     * Gets task_ids
     *
     * @return string[]
     */
    public function getTaskIds()
    {
        return $this->container['task_ids'];
    }

    /**
     * Sets task_ids
     *
     * @param string[] $task_ids Search by specific task ids.
     *
     * @return $this
     */
    public function setTaskIds($task_ids)
    {
        $this->container['task_ids'] = $task_ids;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


