<?php
/**
 * AgendaItemCategoryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AgendaItemCategoryTest Class Doc Comment
 *
 * @category    Class
 * @description AgendaItemCategory
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AgendaItemCategoryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AgendaItemCategory"
     */
    public function testAgendaItemCategory()
    {
    }

    /**
     * Test attribute "back_color"
     */
    public function testPropertyBackColor()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "front_color"
     */
    public function testPropertyFrontColor()
    {
    }

    /**
     * Test attribute "is_private"
     */
    public function testPropertyIsPrivate()
    {
    }

    /**
     * Test attribute "category_type"
     */
    public function testPropertyCategoryType()
    {
    }

    /**
     * Test attribute "minutes_before_reminder"
     */
    public function testPropertyMinutesBeforeReminder()
    {
    }

    /**
     * Test attribute "needs_to_be_confirmed"
     */
    public function testPropertyNeedsToBeConfirmed()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "standard_description"
     */
    public function testPropertyStandardDescription()
    {
    }

    /**
     * Test attribute "standard_duration"
     */
    public function testPropertyStandardDuration()
    {
    }

    /**
     * Test attribute "time_marker"
     */
    public function testPropertyTimeMarker()
    {
    }

    /**
     * Test attribute "use_reminder"
     */
    public function testPropertyUseReminder()
    {
    }

    /**
     * Test attribute "is_urgent"
     */
    public function testPropertyIsUrgent()
    {
    }

    /**
     * Test attribute "is_personal"
     */
    public function testPropertyIsPersonal()
    {
    }

    /**
     * Test attribute "reminder"
     */
    public function testPropertyReminder()
    {
    }
}
