<?php
/**
 * DocumentSessionSnapShotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DocumentSessionSnapShotTest Class Doc Comment
 *
 * @category    Class
 * @description DocumentSessionSnapShot
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentSessionSnapShotTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DocumentSessionSnapShot"
     */
    public function testDocumentSessionSnapShot()
    {
    }

    /**
     * Test attribute "date_time_created"
     */
    public function testPropertyDateTimeCreated()
    {
    }

    /**
     * Test attribute "date_time_modified"
     */
    public function testPropertyDateTimeModified()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "linked_applicants"
     */
    public function testPropertyLinkedApplicants()
    {
    }

    /**
     * Test attribute "linked_assignment"
     */
    public function testPropertyLinkedAssignment()
    {
    }

    /**
     * Test attribute "linked_cadastres"
     */
    public function testPropertyLinkedCadastres()
    {
    }

    /**
     * Test attribute "linked_created_by"
     */
    public function testPropertyLinkedCreatedBy()
    {
    }

    /**
     * Test attribute "linked_document_template"
     */
    public function testPropertyLinkedDocumentTemplate()
    {
    }

    /**
     * Test attribute "linked_employee"
     */
    public function testPropertyLinkedEmployee()
    {
    }

    /**
     * Test attribute "linked_modified_by"
     */
    public function testPropertyLinkedModifiedBy()
    {
    }

    /**
     * Test attribute "linked_notary"
     */
    public function testPropertyLinkedNotary()
    {
    }

    /**
     * Test attribute "linked_property_managers"
     */
    public function testPropertyLinkedPropertyManagers()
    {
    }

    /**
     * Test attribute "linked_vendors"
     */
    public function testPropertyLinkedVendors()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "real_estate_agency_id"
     */
    public function testPropertyRealEstateAgencyId()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }
}
