<?php
/**
 * LinkedRelationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LinkedRelationTest Class Doc Comment
 *
 * @category    Class
 * @description LinkedRelation
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinkedRelationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LinkedRelation"
     */
    public function testLinkedRelation()
    {
    }

    /**
     * Test attribute "association"
     */
    public function testPropertyAssociation()
    {
    }

    /**
     * Test attribute "avatar_url"
     */
    public function testPropertyAvatarUrl()
    {
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "linked_partner"
     */
    public function testPropertyLinkedPartner()
    {
    }

    /**
     * Test attribute "letter_avatar"
     */
    public function testPropertyLetterAvatar()
    {
    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {
    }

    /**
     * Test attribute "membership_number"
     */
    public function testPropertyMembershipNumber()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "phone_mobile"
     */
    public function testPropertyPhoneMobile()
    {
    }

    /**
     * Test attribute "phone_work"
     */
    public function testPropertyPhoneWork()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "street_name_and_number"
     */
    public function testPropertyStreetNameAndNumber()
    {
    }

    /**
     * Test attribute "together_with_partner"
     */
    public function testPropertyTogetherWithPartner()
    {
    }

    /**
     * Test attribute "type_of_relation"
     */
    public function testPropertyTypeOfRelation()
    {
    }
}
