<?php
/**
 * MailHistorySnapShotTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MailHistorySnapShotTest Class Doc Comment
 *
 * @category    Class
 * @description MailHistorySnapShot
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MailHistorySnapShotTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MailHistorySnapShot"
     */
    public function testMailHistorySnapShot()
    {
    }

    /**
     * Test attribute "date_time_sent"
     */
    public function testPropertyDateTimeSent()
    {
    }

    /**
     * Test attribute "matched_property_count"
     */
    public function testPropertyMatchedPropertyCount()
    {
    }

    /**
     * Test attribute "matched_properties"
     */
    public function testPropertyMatchedProperties()
    {
    }
}
