<?php
/**
 * PersonTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PersonTest Class Doc Comment
 *
 * @category    Class
 * @description Person
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Person"
     */
    public function testPerson()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "address_line"
     */
    public function testPropertyAddressLine()
    {
    }

    /**
     * Test attribute "bank_account"
     */
    public function testPropertyBankAccount()
    {
    }

    /**
     * Test attribute "city_of_birth"
     */
    public function testPropertyCityOfBirth()
    {
    }

    /**
     * Test attribute "civil_state"
     */
    public function testPropertyCivilState()
    {
    }

    /**
     * Test attribute "country_iso2_of_birth"
     */
    public function testPropertyCountryIso2OfBirth()
    {
    }

    /**
     * Test attribute "date_of_birth"
     */
    public function testPropertyDateOfBirth()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "email_addresses"
     */
    public function testPropertyEmailAddresses()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {
    }

    /**
     * Test attribute "identification_card"
     */
    public function testPropertyIdentificationCard()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "middle_name"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "name_letters"
     */
    public function testPropertyNameLetters()
    {
    }

    /**
     * Test attribute "nickname"
     */
    public function testPropertyNickname()
    {
    }

    /**
     * Test attribute "passport_photo_blob"
     */
    public function testPropertyPassportPhotoBlob()
    {
    }

    /**
     * Test attribute "phone_numbers"
     */
    public function testPropertyPhoneNumbers()
    {
    }

    /**
     * Test attribute "postal_address"
     */
    public function testPropertyPostalAddress()
    {
    }

    /**
     * Test attribute "postal_address_differs_visit_address"
     */
    public function testPropertyPostalAddressDiffersVisitAddress()
    {
    }

    /**
     * Test attribute "salutation"
     */
    public function testPropertySalutation()
    {
    }

    /**
     * Test attribute "social_media"
     */
    public function testPropertySocialMedia()
    {
    }

    /**
     * Test attribute "social_security_number"
     */
    public function testPropertySocialSecurityNumber()
    {
    }

    /**
     * Test attribute "spoken_languages"
     */
    public function testPropertySpokenLanguages()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "use_formal_appelation"
     */
    public function testPropertyUseFormalAppelation()
    {
    }

    /**
     * Test attribute "web_address"
     */
    public function testPropertyWebAddress()
    {
    }
}
