<?php
/**
 * SpaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SpaceTest Class Doc Comment
 *
 * @category    Class
 * @description Space
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SpaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Space"
     */
    public function testSpace()
    {
    }

    /**
     * Test attribute "balcony_type"
     */
    public function testPropertyBalconyType()
    {
    }

    /**
     * Test attribute "bathroom_facilities"
     */
    public function testPropertyBathroomFacilities()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "has_stairway"
     */
    public function testPropertyHasStairway()
    {
    }

    /**
     * Test attribute "is_renewed"
     */
    public function testPropertyIsRenewed()
    {
    }

    /**
     * Test attribute "kitchen_type"
     */
    public function testPropertyKitchenType()
    {
    }

    /**
     * Test attribute "living_room_types"
     */
    public function testPropertyLivingRoomTypes()
    {
    }

    /**
     * Test attribute "construction_year"
     */
    public function testPropertyConstructionYear()
    {
    }

    /**
     * Test attribute "kitchen_facilities"
     */
    public function testPropertyKitchenFacilities()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "orientation"
     */
    public function testPropertyOrientation()
    {
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
    }

    /**
     * Test attribute "stove"
     */
    public function testPropertyStove()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
