<?php
/**
 * TasksSearchRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TasksSearchRequestTest Class Doc Comment
 *
 * @category    Class
 * @description TasksSearchRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TasksSearchRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TasksSearchRequest"
     */
    public function testTasksSearchRequest()
    {
    }

    /**
     * Test attribute "category_ids"
     */
    public function testPropertyCategoryIds()
    {
    }

    /**
     * Test attribute "delegate_filter"
     */
    public function testPropertyDelegateFilter()
    {
    }

    /**
     * Test attribute "employee_id"
     */
    public function testPropertyEmployeeId()
    {
    }

    /**
     * Test attribute "employee_ids"
     */
    public function testPropertyEmployeeIds()
    {
    }

    /**
     * Test attribute "include_statistics"
     */
    public function testPropertyIncludeStatistics()
    {
    }

    /**
     * Test attribute "order_by"
     */
    public function testPropertyOrderBy()
    {
    }

    /**
     * Test attribute "status_filter"
     */
    public function testPropertyStatusFilter()
    {
    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {
    }

    /**
     * Test attribute "term_fields"
     */
    public function testPropertyTermFields()
    {
    }

    /**
     * Test attribute "task_ids"
     */
    public function testPropertyTaskIds()
    {
    }
}
