<?php
/**
 * AgendaItemCategoriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AgendaItemCategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgendaItemCategoriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for agendaItemCategoriesArchive
     *
     * Archive selected agendaItemCategory.
     *
     */
    public function testAgendaItemCategoriesArchive()
    {
    }

    /**
     * Test case for agendaItemCategoriesDefineNew
     *
     * Defines a new agendaItemCategory instance, without saving it..
     *
     */
    public function testAgendaItemCategoriesDefineNew()
    {
    }

    /**
     * Test case for agendaItemCategoriesDelete
     *
     * Delete selected agendaItemCategory.
     *
     */
    public function testAgendaItemCategoriesDelete()
    {
    }

    /**
     * Test case for agendaItemCategoriesMoveLinkedAgendaItems
     *
     * .
     *
     */
    public function testAgendaItemCategoriesMoveLinkedAgendaItems()
    {
    }

    /**
     * Test case for agendaItemCategoriesRead
     *
     * Read a single agendaItem Category..
     *
     */
    public function testAgendaItemCategoriesRead()
    {
    }

    /**
     * Test case for agendaItemCategoriesSave
     *
     * Save given agendaItemCategory.
     *
     */
    public function testAgendaItemCategoriesSave()
    {
    }

    /**
     * Test case for agendaItemCategoriesSearch
     *
     * Search for agendaItem categories..
     *
     */
    public function testAgendaItemCategoriesSearch()
    {
    }

    /**
     * Test case for agendaItemCategoriesUnarchive
     *
     * Unarchive selected agendaItemCategory.
     *
     */
    public function testAgendaItemCategoriesUnarchive()
    {
    }

    /**
     * Test case for agendaItemCategoriesUndelete
     *
     * Undelete selected agendaItemCategory.
     *
     */
    public function testAgendaItemCategoriesUndelete()
    {
    }
}
