<?php
/**
 * InvoicesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Web API Swagger specification Kolibri24 API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.1.778.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.17
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * InvoicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoicesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for invoicesArchive
     *
     * Archive selected invoice.
     *
     */
    public function testInvoicesArchive()
    {
    }

    /**
     * Test case for invoicesDefineNew
     *
     * Defines a new invoice instance, without saving it..
     *
     */
    public function testInvoicesDefineNew()
    {
    }

    /**
     * Test case for invoicesDelete
     *
     * Delete selected invoice.
     *
     */
    public function testInvoicesDelete()
    {
    }

    /**
     * Test case for invoicesExport
     *
     * Search for invoices and export result to Excel..
     *
     */
    public function testInvoicesExport()
    {
    }

    /**
     * Test case for invoicesRead
     *
     * Fetch a single invoice..
     *
     */
    public function testInvoicesRead()
    {
    }

    /**
     * Test case for invoicesSave
     *
     * Save given invoice.
     *
     */
    public function testInvoicesSave()
    {
    }

    /**
     * Test case for invoicesSearch
     *
     * Search for invoices..
     *
     */
    public function testInvoicesSearch()
    {
    }

    /**
     * Test case for invoicesSearchAndExport
     *
     * Search for invoices and export result to Excel..
     *
     */
    public function testInvoicesSearchAndExport()
    {
    }

    /**
     * Test case for invoicesUnarchive
     *
     * .
     *
     */
    public function testInvoicesUnarchive()
    {
    }

    /**
     * Test case for invoicesUndelete
     *
     * Undelete selected invoice.
     *
     */
    public function testInvoicesUndelete()
    {
    }
}
